[profile.default]
solc = "0.8.23"
src = 'contracts/evm/src'
out = 'dist/contracts/evm'
libs = ['contracts/evm/lib']

via_ir = true
optimizer_runs = 1000000
eth-rpc-url = 'http://localhost:8545'

fs_permissions = [{ access = "read", path = "dist/contracts" }, { access = "read-write", path = ".forge-snapshots/" }]

extra_output = ['storageLayout']
